### PR TITLE
maint: enable SCRAM support

### LINKED ISSUE #155: SCRAM authentication fails
Hi there,

I'm trying to setup on dyno pgbouncers connecting to our external timescaledb (postgres) instances. It seems as though something on the postgres side of things is not compatible with this pgbouncer. 

I'm seeing the following in the logs:

```
 2022-02-05 03:23:51.296 UTC [59] LOG S-0x556d5e181b30: db1/tsdbadmin@34.231.255.115:34451 new connection to server (from 172.17.142.26:57916)
2022-02-05T03:23:51.301451+00:00 app[web.1]: 2022-02-05 03:23:51.301 UTC [59] LOG S-0x556d5e181b30: db1/tsdbadmin@34.231.255.115:34451 SSL established: TLSv1.3/TLS_AES_256_GCM_SHA384/ECDH=prime256v1
2022-02-05T03:23:51.302486+00:00 app[web.1]: 2022-02-05 03:23:51.302 UTC [59] ERROR S-0x556d5e181b30: db1/tsdbadmin@34.231.255.115:34451 cannot do SCRAM authentication: wrong password type
2022-02-05T03:23:51.302490+00:00 app[web.1]: 2022-02-05 03:23:51.302 UTC [59] LOG S-0x556d5e181b30: db1/tsdbadmin@34.231.255.115:34451 closing because: failed to answer authreq (age=0s)
2022-02-05T03:23:51.324906+00:00 app[web.1]: 2022-02-05 03:23:51.324 UTC [59] LOG C-0x556d5e17ad90: db1/tsdbadmin@127.0.0.1:53106 login attempt: db=db1 user=tsdbadmin tls=no
2022-02-05T03:23:51.324928+00:00 app[web.1]: 2022-02-05 03:23:51.324 UTC [59] LOG C-0x556d5e17ad90: db1/tsdbadmin@127.0.0.1:53106 closing because: pgbouncer cannot connect to server (age=0s)
2022-02-05T03:23:51.324944+00:00 app[web.1]: 2022-02-05 03:23:51.324 UTC [59] WARNING C-0x556d5e17ad90: db1/tsdbadmin@127.0.0.1:53106 pooler error: pgbouncer cannot connect to server
2022-02-05T03:23:51.326682+00:00 app[web.1]: 2022-02-05 03:23:51.326 UTC [59] LOG C-0x556d5e17ad90: db1/tsdbadmin@127.0.0.1:53108 login attempt: db=db1 user=tsdbadmin tls=no
```

I would assume the important bit is the `cannot do SCRAM authentication: wrong password type`. 

Any suggestions on a workaround?

### PR DESCRIPTION
**Pull request by mble-sfdc**
In order to support SCRAM support for the new Heroku Postgres "Essential" plans, we need to shift from MD5 hashed passwords in `auth_file` to plain text. This does not materially change the threat model, as anyone with dyno access can read the passwords from the environment just as well as the file.

See: https://www.pgbouncer.org/config.html#authentication-file-format for more.

This commit switches the `auth_type` to `scram-sha-256` and also pushes `server_tls_sslmode` up to `require` over `prefer`.

Why not use a method like `auth_query`? Exposing something like `pg_authid` or `pg_shadow` in a safe way via a `SECURITY DEFINER` function is extremely challenging in a multi-tenant environment. This may change in the future.

Fixes #155.

Ref: https://gus.my.salesforce.com/a07EE00001rjvVBYAY

Testing Notes:
- Deploy an application to Heroku that connects to an Essential-tier Postgres instance and inserts random numbers into a test table
-  Add this branch's version of the buildpack with `heroku buildpacks:add https://github.com/heroku/heroku-buildpack-pgbouncer.git#17cb11aa1ebabf5d467cb6341c8dfc155533a326`
- Build the app
- Tail the app logs:
```
2024-05-21T14:00:58.410834+00:00 app[conn_test.1]: 2024-05-21 14:00:58.410 UTC [16] LOG S-0x565551b1bb80: db1/u4ifhuflluntg3@54.147.31.50:5432 new connection to server (from 172.16.0.66:44670)
2024-05-21T14:00:58.416864+00:00 app[conn_test.1]: 2024-05-21 14:00:58.416 UTC [16] LOG S-0x565551b1bb80: db1/u4ifhuflluntg3@54.147.31.50:5432 SSL established: TLSv1.3/TLS_AES_256_GCM_SHA384/ECDH=prime256v1
2024-05-21T14:00:59.385069+00:00 app[conn_test.1]: thread id 4 starting..
2024-05-21T14:00:59.385879+00:00 app[conn_test.1]: 2024-05-21 14:00:59.385 UTC [16] LOG C-0x565551b15800: db1/u4ifhuflluntg3@127.0.0.1:50376 login attempt: db=db1 user=u4ifhuflluntg3 tls=no
2024-05-21T14:01:02.385909+00:00 app[conn_test.1]: thread id 5 starting..
2024-05-21T14:01:02.386555+00:00 app[conn_test.1]: 2024-05-21 14:01:02.386 UTC [16] LOG C-0x565551b14ae0: db1/u4ifhuflluntg3@127.0.0.1:52666 closing because: client close request (age=21s)
```

### CODE REVIEW

File: bin/gen-pgbouncer-conf.sh [hunk 1]
```diff
@@ -19,9 +19,9 @@ cat >> "$CONFIG_DIR/pgbouncer.ini" << EOFEOF
 [pgbouncer]
 listen_addr = 127.0.0.1
 listen_port = 6000
-auth_type = md5
+auth_type = scram-sha-256
 auth_file = $CONFIG_DIR/users.txt
-server_tls_sslmode = prefer
```
Comment (binarycleric) [inline bin/gen-pgbouncer-conf.sh:24]: Do we expect this change to break anything? I suspect not now that we support TLS fleet-wide.

Comment (binarycleric) [reply bin/gen-pgbouncer-conf.sh:24]: We've seen a few GitHub Issues in the past where customers are using the buildpack to connect to RDS/Crunchy/etc. I hope that this change doesn't impact that as well but I would assume they are also supporting TLS and agree customers have bigger problems if they are not for some reason.

**Review by binarycleric — APPROVED** [review]
This change looks straight-forward enough to me and I'm glad that we're moving away from MD5ed passwords. I spoke to Troy on Slack and he has verified that the buildpack works against `essential-0`, `mini`, and `standard-0` addons so we can be confident it'll work against the fleet.

File: bin/gen-pgbouncer-conf.sh
Comment (dhagberg-sf) [inline bin/gen-pgbouncer-conf.sh:1]: Guessing this will never be used on a multiuser system, but if it's possible, setting a `umask` up at the top to ensure the `users.txt` file is ONLY readable by the intended user/group would be a good practice.  But this is likely going in a single-user container so prob not necessary.

**Review by dhagberg-sf — APPROVED** [review]
Thanks for the notes on testing - seems quite reasonable.

**Comment by dhagberg-sf** [comment]
So double checked that SCRAM has been supported since pg10, so that should not be an issue.

But we'll need to be quite careful in our release notes (significant version bump?) to indicate the database must be configured to support scram auth in pg_hba.conf (which will be true for all heroku dbs, but as indicated above sometimes this buildpack might be used for other db targets).

File: test/gen-pgbouncer-conf.bats [hunk 2]
```diff
@@ -34,7 +34,8 @@ teardown_file() {
     assert_success
     cat "$PGBOUNCER_CONFIG_DIR/pgbouncer.ini"
     assert_line 'Setting DATABASE_URL_PGBOUNCER config var'
-    assert grep "server_tls_sslmode = prefer" "$PGBOUNCER_CONFIG_DIR/pgbouncer.ini"
+    assert grep "auth_type = scram-sha-256" "$PGBOUNCER_CONFIG_DIR/pgbouncer.ini"
+    assert grep "server_tls_sslmode = require" "$PGBOUNCER_CONFIG_DIR/pgbouncer.ini"
     assert grep "db1= host=host dbname=name?query port=5432" "$PGBOUNCER_CONFIG_DIR/pgbouncer.ini"
     assert grep "db2= host=host2 dbname=dbname port=7777" "$PGBOUNCER_CONFIG_DIR/pgbouncer.ini"
     assert grep "user" "$PGBOUNCER_CONFIG_DIR/users.txt"
```
Comment (edmorley) [inline test/gen-pgbouncer-conf.bats:41]: (optional) Should these `users.txt` assertions check the password is present after the username too, now it's being written directly? 

eg `assert grep "user pass" "$PGBOUNCER_CONFIG_DIR/users.txt"`

(And for bonus points updating `user2`'s password to `pass2` to verify the correct passwords are being written for each user?)

File: Changelog.md [hunk 3]
```diff
@@ -1,4 +1,5 @@
 ## Unreleased
+* Support SCRAM authentication, use plain passwords in auth_file
```
Comment (edmorley) [inline Changelog.md:2]: (optional) Would it be worth mentioning the change in `server_tls_sslmode` in the changelog here (as a separate bullet) too?

**Review by edmorley — APPROVED** [review]
This looks great from a buildpack implementation point of view (I'll leave the Postgres side of the review to others). When this is released, do you think there is a need for a public changelog post on https://devcenter.heroku.com/changelog ?

File: test/gen-pgbouncer-conf.bats (hunk 2 above)
Comment (mble-sfdc) [reply test/gen-pgbouncer-conf.bats]: Yep, added!

**Comment by troycoll** [comment]
@edmorley we've got a changelog drafted and approved, will publish as soon as this version is released.

**Comment by edmorley** [comment]
@troycoll Are you ready for me to perform the release?

**Comment by troycoll** [comment]
@edmorley yep fire away! I'll publish the Changelog now

**Comment by edmorley** [comment]
Released via #194.
